languages = [
    "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Azerbaijani", "Bengali", "Bosnian", "Bulgarian",
    "Catalan", "Chinese (Simplified)", "Chinese (Traditional)", "Croatian", "Czech", "Danish", "Dutch",
    "English", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek",
    "Gujarati", "Hausa", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Italian", "Japanese",
    "Kannada", "Kazakh", "Korean", "Latvian", "Lithuanian", "Macedonian", "Malay", "Malayalam", "Marathi",
    "Nepali", "Norwegian", "Persian", "Polish", "Portuguese", "Punjabi", "Romanian", "Russian", "Serbian",
    "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian",
    "Urdu", "Vietnamese", "Zulu"
]

languages_weights = {
    "Afrikaans": 1,
    "Albanian": 1,
    "Amharic": 1,
    "Arabic": 1,
    "Armenian": 1,
    "Azerbaijani": 1,
    "Bengali": 1,
    "Bosnian": 1,
    "Bulgarian": 1,
    "Catalan": 1,
    "Chinese (Simplified)": 1,
    "Chinese (Traditional)": 1,
    "Croatian": 1,
    "Czech": 1,
    "Danish": 1,
    "Dutch": 1,
    "English": 1,
    "Estonian": 1,
    "Filipino": 1,
    "Finnish": 1,
    "French": 1,
    "Galician": 1,
    "Georgian": 1,
    "German": 1,
    "Greek": 1,
    "Gujarati": 1,
    "Hausa": 1,
    "Hebrew": 1,
    "Hindi": 1,
    "Hungarian": 1,
    "Icelandic": 1,
    "Indonesian": 1,
    "Italian": 1,
    "Japanese": 1,
    "Kannada": 1,
    "Kazakh": 1,
    "Korean": 1,
    "Latvian": 1,
    "Lithuanian": 1,
    "Macedonian": 1,
    "Malay": 1,
    "Malayalam": 1,
    "Marathi": 1,
    "Nepali": 1,
    "Norwegian": 1,
    "Persian": 1,
    "Polish": 1,
    "Portuguese": 1,
    "Punjabi": 1,
    "Romanian": 1,
    "Russian": 1,
    "Serbian": 1,
    "Slovak": 1,
    "Slovenian": 1,
    "Spanish": 1,
    "Swahili": 1,
    "Swedish": 1,
    "Tamil": 1,
    "Telugu": 1,
    "Thai": 1,
    "Turkish": 1,
    "Ukrainian": 1,
    "Urdu": 1,
    "Vietnamese": 1,
    "Zulu": 1
}
